version: "3"

services:
  web:
    build: ./vote
    command: python app.py
    volumes:
     - .:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - "db-data:/var/lib/mysqldata/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier: